nfq_weather:
    provider: delegating
    providers:
        openweathermap:
            api_key: '7bf471179d2772ee60ecd68ede58ff8f'
        delegating:
            providers:
                - yahoo
                - openweathermap
